"""pbr_journal_pull_report.py - the journal pull list as a standalone report (rule 21).

Reads the Journal_Pull sheet of the shipped register with python-calamine (rule 19.8) and writes
reports/Journal_Pull_<ver>.md and .xlsx. The workbook is the record; this is the working copy that goes to
Finance with the pull request. Nothing is recomputed here, so the report cannot disagree with the register.

Usage: python3 pbr_journal_pull_report.py [register.xlsx] [outdir]
"""
import datetime as dt, os, re, sys
from decimal import Decimal, ROUND_HALF_UP
from python_calamine import CalamineWorkbook
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pbr_unidentified_queue import latest_register  # noqa

REG = sys.argv[1] if len(sys.argv) > 1 else latest_register()
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, 'reports')
D = lambda x: Decimal(str(x)).quantize(Decimal('0.01'), ROUND_HALF_UP)
MONEY = '$#,##0.00;($#,##0.00);"-"'


def main():
    wb = CalamineWorkbook.from_path(REG)
    cfg = {r[0]: r[1] for r in wb.get_sheet_by_name('Config').to_python(skip_empty_area=False) if r and r[0]}
    ver = str(cfg.get('WORKBOOK_VERSION', 'v?'))
    JP = wb.get_sheet_by_name('Journal_Pull').to_python(skip_empty_area=False)
    hdr = [str(c) for c in JP[3]]
    a, b = (int(x) for x in re.match(r'(\d+):(\d+)', str(cfg['JOURNAL_PULL'])).groups())
    body = [r for r in JP[a - 1:b]]
    preamble = [str(JP[1][0])]
    tiers = {}
    for r in body:
        t = str(r[0]); tiers.setdefault(t, [0, Decimal(0), Decimal(0), 0])
        tiers[t][0] += 1; tiers[t][1] += D(r[5]); tiers[t][2] += D(r[6]); tiers[t][3] += int(r[4])
    absA = sum(abs(D(r[5])) for r in body if str(r[0]).startswith('A'))
    stamp = dt.date.today().strftime('%d-%b-%Y')
    md = [f'# Journal pull list, Parks Branch register FY2026/27 {ver} ({stamp})', '',
          f'**Position:** {len(body)} TechOne document files carry the {sum(int(r[4]) for r in body):,} journal lines on the register. '
          f'{tiers.get("A Pull required", [0])[0]} sit in Tier A (no attachment, ${absA:,.2f} absolute net). '
          f'{sum(1 for r in body if str(r[8]) == "High" and str(r[0])[0] in "AB")} document(s) across Tiers A and B carry an unanswered question and are the ones worth working first.', '',
          preamble[0], '',
          '## By tier', '', '| Tier | Documents | Register lines | Net in scope | Gross in scope |', '|---|---:|---:|---:|---:|']
    for t in sorted(tiers):
        n, net, gross, ln = tiers[t]
        md.append(f'| {t} | {n} | {ln:,} | {net:,.2f} | {gross:,.2f} |')
    for t in sorted(tiers):
        rows = [r for r in body if str(r[0]) == t]
        md += ['', f'## {t}', '', '| # | Document file | Journal ref(s) | Period(s) | Lines | Net in scope | Gross | Att | Pull value | Why it matters | Sections | Top accounts | Top PKs |',
               '|---|---|---|---|---:|---:|---:|---|---|---|---|---|---|']
        for k, r in enumerate(rows, 1):
            md.append(f'| {k} | **{r[1]}** | {r[2]} | {r[3]} | {int(r[4])} | {D(r[5]):,.2f} | {D(r[6]):,.2f} | {r[7]} | {r[8]} | {str(r[9])[:230]} | {str(r[10])[:60]} | {r[11]} | {r[12]} |')
    md += ['', '## How to use', '',
           '1. Work Tier A top down and pull one TechOne Document Line Table per **document file**, not per journal reference: one export covers every reference on the file.',
           '2. Screen each export against Journal_Sources in the PS & WP register before capture; a re-pull is audited leg by leg and never re-captured (rule 12).',
           '3. Embed each new document verbatim with leg-level in-scope flags, prove it nets to zero and that each in-scope leg sum ties its own register lines, then refresh this list (pipeline, per journal batch).',
           '4. Tier B needs no pull: sight the TechOne attachment on the document file. Tier C is RJ reversing journals, read as a pair under rules 5 and 6. Tier D is already embedded in the PS & WP register.',
           '', f'Source: `{os.path.basename(REG)}`, Journal_Pull rows {a}:{b}; generated by `toolkit/branch/pbr_journal_pull_report.py`.']
    os.makedirs(OUT, exist_ok=True)
    open(os.path.join(OUT, f'Journal_Pull_{ver}.md'), 'w', encoding='utf-8').write('\n'.join(md) + '\n')

    xw = Workbook(); ws = xw.active; ws.title = 'Journal_Pull'
    hf = Font(name='Cambria', bold=True, color='FFFFFF'); fill = PatternFill('solid', fgColor='1F3864')
    ws.append([f'Journal pull list, Parks Branch register FY2026/27 {ver} ({stamp}): {len(body)} document files, '
               f'{tiers.get("A Pull required", [0])[0]} to pull, ${absA:,.2f} absolute net.'])
    ws.append([preamble[0]]); ws.append([])
    ws.append(hdr)
    for c in ws[4]:
        c.font = hf; c.fill = fill
    for r in body:
        ws.append(list(r[:len(hdr)]))
        ws.cell(ws.max_row, 6).number_format = MONEY; ws.cell(ws.max_row, 7).number_format = MONEY
    for col, w in zip('ABCDEFGHIJKLMN', [30, 14, 30, 10, 12, 16, 16, 8, 11, 80, 26, 26, 24, 60]):
        ws.column_dimensions[col].width = w
    ws.freeze_panes = 'A5'
    for c in ws[1] + ws[2]:
        c.alignment = Alignment(wrap_text=False)
    xw.save(os.path.join(OUT, f'Journal_Pull_{ver}.xlsx'))
    print(f'{len(body)} document files -> {OUT}/Journal_Pull_{ver}.md and .xlsx')
    for t in sorted(tiers):
        n, net, gross, ln = tiers[t]
        print(f'  {t:42} {n:3} documents  {ln:5,} lines  net ${net:>14,.2f}')
    for r in [r for r in body if str(r[0]).startswith('A')] + [r for r in body if str(r[0]).startswith('B') and str(r[8]) == 'High']:
        print(f"    {str(r[0])[:1]} {str(r[8]):6} {r[1]:9} {str(r[2])[:26]:26} lines {int(r[4]):5} net ${D(r[5]):>13,.2f}  {str(r[9])[:96]}")


if __name__ == '__main__':
    main()
